### ISSUE TITLE
프론트엔드 -  wireframe 설계

### ISSUE THREAD

**Issue by 0BVer** [Back-to-Beginner/capstone#17]
- [ ] [Figma](https://www.figma.com) 화면 설계
-  [Figma 사용법 1](https://cucat.tistory.com/51)
- [Figma 사용법 2](https://blog.naver.com/PostView.naver?blogId=mu-ze&logNo=222279003007)
- [Figma 사용법 3](https://webactually.com/2021/01/18/개발자가-알아야-할-피그마의-모든-것/)

- [ ] [zeplin](https://zeplin.io) 으로 figma에서 생성한 화면 디자인 코드화
- [zeplin 사용법 1](https://m.blog.naver.com/o_cloud/221855163039)
- [zeplin 사용법 2](https://blog.rightbrain.co.kr/?p=8427)

figma와 zeplin을 사용해서 화면을 보다 쉽게 설계하고, 바로 코드로 추출하여 화면 디자인에 대한 부분을 쉽게 해결 가능

**Comment by Daehyeon98** [comment]
1. Figma
![개시물 등록](https://user-images.githubusercontent.com/101495251/163737724-273ed264-608f-4a08-89d8-10c7983783dd.PNG)
![정보수정](https://user-images.githubusercontent.com/101495251/163737730-868a146f-a69e-4bf8-8ac8-7f3ce751385d.PNG)

- Figma를 통해 초기 UI 디자인 제작 완료

2. Zeplin
![제플린3](https://user-images.githubusercontent.com/101495251/163737743-cb6c7d2d-f76f-4adb-a48c-4aeede0f16fd.PNG)
![제플린4](https://user-images.githubusercontent.com/101495251/163737748-b9baefff-6886-456b-9495-cd7d2eece3c7.PNG)

- Figma와 Zeplin 연동 완료
- Zeplin에 Figma에서 작업한 UI 확인 완료
- 항목 별 코드 반환 확인 완료
- BUT, 모든 항목의 코드가 완벽한 것이 아니기에 추가적인 보완작업 후 코드 사용 요망
