### ISSUE TITLE
프론트엔드 - 구글맵 api 연동 및 테스트

### ISSUE THREAD

**Issue by 0BVer** [Back-to-Beginner/capstone#19]
[구글맵 API](https://developers.google.com/maps/documentation/javascript/examples/places-searchbox)
- [x]  위 링크의 API를 클론 코드를 통해 화면에 띄우기
- [ ]  검색을 통해 나온 위치에 대한 이름과 좌표를 `console.log()`를 통해 콘솔에 출력

**Comment by Daehyeon98** [comment]
지도 띄우기 성공
- 검색 박스, 좌표 설정 기능 현재 보류

**Comment by 0BVer** [comment]
> 지도 띄우기 성공
> 
> * 검색 박스, 좌표 설정 기능 현재 보류

와우 개쩌러
보류한것만 되면 기능은 거의 끝나네
