### ISSUE TITLE
유사 사례 분석 - 최대현

### ISSUE THREAD

**Issue by 0BVer** [Back-to-Beginner/capstone#5]
@Daehyeon98 이곳에 유사사례 분석해서 이글 밑에 이어서 작성 후 readme 파일에 정리

**Comment by Daehyeon98** [comment]
.

**Comment by Daehyeon98** [comment]
다른 연구 사례
1. 항공편 정보제공 사이트
1) 항공정보포털시스템 :  https://www.airportal.go.kr/life/airinfo/RaSkeFrmMain.jsp  
- 출발공항, 도착공항, 특정 출발/도착공학 미선택 시 지역, 국가 상관 없이 모든 공항 조회
![항공정보포털시스템](https://user-images.githubusercontent.com/101495251/158343593-77a30eab-5e6e-40e8-a9dd-1146503aa088.PNG)

2) FlightAware : https://ko.flightaware.com/ 
- 항공편 추적기 / 항공편 상태
- 모든 항공 결정에 도움이 되는 정확하고 실행 가능한 고급 데이터와 통찰력을 제공하는 선도 업체
-
![FlightAware](https://user-images.githubusercontent.com/101495251/158343806-6020e31b-e262-444f-819e-f53deae6961b.PNG)


2. 여행 커뮤니티
1) 여행 커뮤니티 - 누리일주
- 호텔, 항공권, 레스토랑, 여행일정, 국내/해외여행 등의 정보를 공유할 수 있는 커뮤니티 사이트
http://noory.kr/community/  
![여행 커뮤니티(누리일주)](https://user-images.githubusercontent.com/101495251/158343923-c50a691f-9371-4e3a-aca9-3a8d4f64e44a.PNG)

2) 여행-국내 갤러리 -dcinside
- 국내 여행과 관련된 정보를 서로 공유할 수 있음
https://gall.dcinside.com/board/lists/?id=travel 
![여행-국내 갤러리(디시인사이드)](https://user-images.githubusercontent.com/101495251/158344070-150303c2-d364-4b90-a200-ec2652dc22e7.PNG)


* 우리 서비스의 차별점
- 항공정보포털시스템 같은 경우는 커뮤니티가 따로 존재하지 않았음.
- FlightAware 같은 경우는 커뮤니티가 따로 존재하였음.
   - 하지만, 우리가 목표로 하고 있는 항공편에 대한 정보 공유, 여행지에 대한 정보 공유에 대한 내용은 X
   - 커뮤니티를 살펴보니 거의다 관련없는 내용이었고 운영이 잘 안되는 상황
 
- 여행 커뮤니티는 사용자들이 직접 가본 여행지에 대한 자신만의 정보(꿀팁) 등이 게시글로 올라와있음.
- 커뮤니티를 사용해본 결과, 모든 내용이 유용하지는 않았지만 참고할만한 내용들이 있었음.
- 이러한 게시물이 항공편 정보제공 사이트에 같이 활성화가 되어 있으면 항공사, 운행시간 등을 수월하게
  선택하고, 여행지도 폭 넓게 알아갈 수 있으며 관련 명소 또한 한 번에 쉽게 정보를 얻을 수 있을 것
- 따라서, 우리의 서비스의 차별점은 현재 지금은 항공편 정보제공 사이트, 여행 커뮤니티가 따로 존재하는 것을 확인하였고, 따라서 이러한 사이트들을 하나의 사이트에 기능을 모두 제공한다면 좋을 것
- 여행 커뮤니티에서는 보통 여행지에 대한 정보를 공유하는 내용이 많은데, 해외여행을 가보지 않은 나같은 사람에게는 항공사, 운행시간, 가격 등 또한 정보가 부족하고 매우 중요하기 때문에 정보(꿀팁)등을 쉽게 얻고 결정을 할 수 있다는 장점이 있음
- 또한 가격변동에 대한 정보도 제공해주기에 여행일정을 보다 수월하게 결정할 수 있을 것
